### ISSUE TITLE
Role missing from generateimage function definition in serverless.yaml

### ISSUE THREAD

**Issue by stevezxu** [SanderKnape/comparing-serverless-and-sam#1]
`role: GenerateImageRole` is missing from `functions.generateimage` in serverless.yaml. As the result, generateimage is denied access to the S3. Adding the missing role fixed the issue for me.

```
functions:
  generateimage:
    role: GenerateImageRole
    handler: lambda/generate-image/index.handler
    environment:
```
btw, great blog  and this repo. Thanks for putting this together.
