### ISSUE TITLE
Fn::Join

### ISSUE THREAD

**Issue by hounded** [SanderKnape/comparing-serverless-and-sam#2]
Hi SanderKnape, 

I was reading your blog, thanks for that. However I have run into a problem with serverless, how would you over come the following? 
I'm trying to implement a serverless dynamodb with scaling. How do I handle the join function with out the implementation !Join (not implemented in serverless) . Could you advise on how I could write this cloud formation in serverless, else I see no other way than SAM 

Cloud formation : 
```yaml
WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 15
      MinCapacity: 5
      ResourceId: !Join
        - /
        - - table
          - !Ref readings
      RoleARN: !GetAtt ScalingRole.Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
```
Serverless : 
```yaml 
WriteCapacityScalableTarget:
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 50
      MinCapacity: 5
      ResourceId: Fn::Join:
        - /
        - - table
          - Fn::Ref:readings
      RoleARN:
        Fn::GetAtt
          - ScalingRole
          - Arn
      ScalableDimension: dynamodb:table:WriteCapacityUnits
      ServiceNamespace: dynamodb
```
